name: imm_app
description: Inventory Movement Management App
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  # Firebase dependencies
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  # Removed firebase_storage for now due to web compatibility issues

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
