// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4YHmfnKN795eH-d0IOc6dd4ge0LtXM8U',
    appId: '1:355380922363:web:a7bea4ac57ee4a1c',
    messagingSenderId: '355380922363',
    projectId: 'inventory-management-app-e71c1',
    authDomain: 'inventory-management-app-e71c1.firebaseapp.com',
    storageBucket: 'inventory-management-app-e71c1.firebasestorage.app',
    measurementId: 'G-H8J9K0L1M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4YHmfnKN795eH-d0IOc6dd4ge0LtXM8U',
    appId: '1:355380922363:android:1947dff226c63667186d5e',
    messagingSenderId: '355380922363',
    projectId: 'inventory-management-app-e71c1',
    storageBucket: 'inventory-management-app-e71c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4YHmfnKN795eH-d0IOc6dd4ge0LtXM8U',
    appId: '1:355380922363:ios:c9d0e1f2g3h4i5j6',
    messagingSenderId: '355380922363',
    projectId: 'inventory-management-app-e71c1',
    storageBucket: 'inventory-management-app-e71c1.firebasestorage.app',
    iosBundleId: 'com.imm.app.immApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4YHmfnKN795eH-d0IOc6dd4ge0LtXM8U',
    appId: '1:355380922363:ios:c9d0e1f2g3h4i5j6',
    messagingSenderId: '355380922363',
    projectId: 'inventory-management-app-e71c1',
    storageBucket: 'inventory-management-app-e71c1.firebasestorage.app',
    iosBundleId: 'com.imm.app.immApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4YHmfnKN795eH-d0IOc6dd4ge0LtXM8U',
    appId: '1:355380922363:web:a7bea4ac57ee4a1c',
    messagingSenderId: '355380922363',
    projectId: 'inventory-management-app-e71c1',
    authDomain: 'inventory-management-app-e71c1.firebaseapp.com',
    storageBucket: 'inventory-management-app-e71c1.firebasestorage.app',
    measurementId: 'G-H8J9K0L1M2',
  );
}